/*
Copyright 2022 Olivier Mengué

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package codegen_test

import (
	"github.com/dolmen-go/codegen"
	"log"
	"os"
)

func Example() {
	const template = `// Code generated by example_test.go; DO NOT EDIT.
{{/**/}}//+build {{.}}

package main

import "os"

func main() {
	os.Stdout.WriteString("Hello, {{.}}!\n")
}
`

	tmpl := codegen.MustParse(template)
	for _, tag := range os.Args[1:] {
		f := "main_" + tag + ".go"
		if err := tmpl.CreateFile(f, tag); err != nil {
			log.Fatal(err)
		}
		log.Printf("File %s created.\n", f)
	}
}
