name: Go
on: [push]
jobs:

  build:
    name: Build&test
    runs-on: ubuntu-latest

    env:
      GO111MODULE: 'on'
    strategy:
      matrix:
        go:
          - 'stable'
          - 'oldstable'
          - '1.22'
          - '1.21'
          - '1.20'
          - '1.19'
          - '1.18'
          - '1.17'
          - '1.16'
          - '1.15'
          - '1.14'
          - '1.13'
          - '1.12'

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v -covermode=atomic -coverprofile=coverage.out ./...

    - name: Upload coverage to Codecov.io
      # https://github.com/codecov/codecov-action
      # https://docs.codecov.com/docs/quick-start
      uses: codecov/codecov-action@v4
      with:
        # https://github.com/dolmen-go/codegen/settings/secrets/actions
        token: ${{ secrets.CODECOV_TOKEN }}
