name: Go
on: [push]
jobs:

  build:
    name: Build&test
    runs-on: ubuntu-latest

    env:
      GO111MODULE: 'on'
    strategy:
      matrix:
        go:
          - '1.12'
          - '1.13'
          - '1.14'
          - '1.16'
          - '1.17'
          - '1.18'
          - '1.19'
          - '1.20'
          - '1.21'
          - '1.22'

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v -covermode=atomic -coverprofile=coverage.out ./...

    - name: Upload coverage to Codecov.io
      uses: codecov/codecov-action@v4
